### ISSUE TITLE
help，/discov/discovStudio/getDouyinAccount

### ISSUE THREAD

**Issue by qtcks** [woftsun/countdown#1]
// 使用UID交换抖音账号
export const changeDyAccount = async (id) => {
  const params = { douyinId: id }
  const url = baseUrl + "/discov/discovStudio/getDouyinAccount"
  return await get(url, {}, params)
}

请问这里的baseUrl 是什么呀？
能告知完整的curl吗？

**Comment by woftsun** [comment]
这个是我之前别的项目上改了下  无用代码已删除 重新拉一下就好了
